# ============================================================
# VibeSport Backend - Schemas 包
# ============================================================
from schemas.schemas import (
    UserRegister,
    UserLogin,
    TokenResponse,
    UserOut,
    UserUpdate,
    ChangePassword,
    RunningLogCreate,
    RunningLogUpdate,
    RunningLogOut,
    FitnessLogCreate,
    FitnessLogUpdate,
    FitnessLogOut,
    WeightLogCreate,
    WeightLogUpdate,
    WeightLogOut,
    ExerciseTypeOut,
    ExerciseTypeCreate,
    RunningStats,
    FitnessStats,
    WeightStats,
    DashboardData,
    MessageResponse,
    PaginatedResponse,
)

__all__ = [
    "UserRegister",
    "UserLogin",
    "TokenResponse",
    "UserOut",
    "UserUpdate",
    "ChangePassword",
    "RunningLogCreate",
    "RunningLogUpdate",
    "RunningLogOut",
    "FitnessLogCreate",
    "FitnessLogUpdate",
    "FitnessLogOut",
    "WeightLogCreate",
    "WeightLogUpdate",
    "WeightLogOut",
    "ExerciseTypeOut",
    "ExerciseTypeCreate",
    "RunningStats",
    "FitnessStats",
    "WeightStats",
    "DashboardData",
    "MessageResponse",
    "PaginatedResponse",
]
